Write a program, which would download the data from the provided link, and then read the data and convert that into properly structured data and return it in Excel format.

Note - Write comments wherever necessary explaining the code written.

Link - https://raw.githubusercontent.com/Biuni/PokemonGO-Pokedex/master/pokedex.json

- **Data Attributes**
- id: Identification Number - int 
- num: Number of the Pokémon in the official Pokédex - int 
- name: Pokémon name - string 
- img: URL to an image of this Pokémon - string 
- type: Pokémon type -string 
- height: Pokémon height - float
- weight: Pokémon weight - float 
- candy: type of candy used to evolve Pokémon or given when transferred - string 
- candy_count: the amount of candies required to evolve - int
- egg: Number of kilometers to travel to hatch the egg - float 
- spawn_chance: Percentage of spawn chance (NEW) - float 
- avg_spawns: Number of this pokemon on 10.000 spawns (NEW) - int
- spawn_time: Spawns most active at the time on this field. Spawn times are the same for all time zones and are expressed in local time. (NEW) - “minutes: seconds” 
- multipliers: Multiplier of Combat Power (CP) for calculating the CP after evolution See below - list of int
- weakness: Types of Pokémon this Pokémon is weak to - list of strings 
- next_evolution: Number and Name of successive evolutions of Pokémon - list of dict 
- prev_evolution: Number and Name of previous evolutions of Pokémon - - list of dict

In [1]:
import requests as req
import pandas as pd
import numpy as np


url = "https://raw.githubusercontent.com/Biuni/PokemonGO-Pokedex/master/pokedex.json"

resp = req.get(url)

json_data = resp.json() # Download data in the form of json

data_pokemon = json_data["pokemon"] # from attribute 'pokemon' extract information for data

df_pokemon = pd.DataFrame(data_pokemon) # pandas dataframe from json format
file_name = "pokemon_pokedex.xlsx"
df_pokemon.to_excel(file_name, index=False)

In [2]:
df_pokemon.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.690,69.0,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.042,4.2,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.017,1.7,11:30,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.253,25.3,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.012,1.2,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"

In [3]:
df_pokemon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              151 non-null    int64
 1   num             151 non-null    object
 2   name            151 non-null    object
 3   img             151 non-null    object
 4   type            151 non-null    object
 5   height          151 non-null    object
 6   weight          151 non-null    object
 7   candy           151 non-null    object
 8   candy_count     70 non-null     float64
 9   egg             151 non-null    object
 10  spawn_chance    151 non-null    float64
 11  avg_spawns      151 non-null    float64
 12  spawn_time      151 non-null    object
 13  multipliers     70 non-null     object
 14  weaknesses      151 non-null    object
 15  next_evolution  70 non-null     object
 16  prev_evolution  72 non-null     object
dtypes: float64(3), int64(1), object(13)
memory usage: 20.2+ KB

In [4]:
df_pokemon['num'] = df_pokemon['num'].astype(int)

In [5]:
df_pokemon['height'] = df_pokemon['height'].str.replace(' m', '').astype(float)
df_pokemon['weight'] = df_pokemon['weight'].str.replace(' kg', '').astype(float)

In [6]:
df_pokemon['candy_count'] = df_pokemon['candy_count'].fillna(0)

In [7]:
df_pokemon['candy_count'] = df_pokemon['candy_count'].astype(int)

In [8]:
df_pokemon['egg'] = df_pokemon['egg'].replace('Not in Eggs', 0)
df_pokemon['egg'] = df_pokemon['egg'].replace('Omanyte Candy', 0)

In [9]:
df_pokemon['egg'] = df_pokemon['egg'].str.replace(' km', '').astype(float)

In [10]:
df_pokemon['egg'] = df_pokemon['egg'].fillna(0)

In [11]:
df_pokemon

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
0,1,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71,6.9,Bulbasaur Candy,25,2.0,0.6900,69.00,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
1,2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99,13.0,Bulbasaur Candy,100,0.0,0.0420,4.20,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01,100.0,Bulbasaur Candy,0,0.0,0.0170,1.70,11:30,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
3,4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61,8.5,Charmander Candy,25,2.0,0.2530,25.30,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09,19.0,Charmander Candy,100,0.0,0.0120,1.20,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,[Dragon],1.80,3.3,Dratini Candy,25,10.0,0.3000,30.00,06:41,"[1.83, 1.84]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,[Dragon],3.99,16.5,Dratini Candy,100,0.0,0.0200,2.00,11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]"
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"[Dragon, Flying]",2.21,210.0,Dratini Candy,0,0.0,0.0011,0.11,23:38,None,"[Ice, Rock, Dragon, Fairy]",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1..."
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,[Psychic],2.01,122.0,None,0,0.0,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,[Psychic],0.41,4.0,None,0,0.0,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN

# The proper code with function

In [12]:
import requests as req
import pandas as pd
import numpy as np

def download_pokemon(url):
    resp = req.get(url)
    json_data = resp.json()
    data_pokemon = json_data["pokemon"]
    return pd.DataFrame(data_pokemon)

def save_2_excel(df, filename):
    df.to_excel(file_name, index=False)
    print(f"The Dataframe saved successfully as {filename}")

In [37]:
url = "https://raw.githubusercontent.com/Biuni/PokemonGO-Pokedex/master/pokedex.json"
df_poke = download_pokemon(url)

In [38]:
df_poke.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.690,69.0,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.042,4.2,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.017,1.7,11:30,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.253,25.3,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.012,1.2,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"

In [39]:
df_poke.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              151 non-null    int64
 1   num             151 non-null    object
 2   name            151 non-null    object
 3   img             151 non-null    object
 4   type            151 non-null    object
 5   height          151 non-null    object
 6   weight          151 non-null    object
 7   candy           151 non-null    object
 8   candy_count     70 non-null     float64
 9   egg             151 non-null    object
 10  spawn_chance    151 non-null    float64
 11  avg_spawns      151 non-null    float64
 12  spawn_time      151 non-null    object
 13  multipliers     70 non-null     object
 14  weaknesses      151 non-null    object
 15  next_evolution  70 non-null     object
 16  prev_evolution  72 non-null     object
dtypes: float64(3), int64(1), object(13)
memory usage: 20.2+ KB

In [40]:
df_poke['candy_count'] = df_poke['candy_count'].fillna(0)  # Handling Nan value
df_poke['egg'] = df_poke['egg'].replace('Not in Eggs', 0)  # replacing string to 0
df_poke['egg'] = df_poke['egg'].replace('Omanyte Candy', 0) # replacing string to 0

In [41]:
df_poke['egg'] = df_poke['egg'].fillna(0)  # Handling Nan value

In [42]:
df_poke['num'] = df_poke['num'].astype(int)
df_poke['height'] = df_poke['height'].str.replace(' m', '').astype(float)

In [43]:
df_poke['weight'] = df_poke['weight'].str.replace(' kg', '').astype(float)

In [44]:
df_poke['candy_count'] = df_poke['candy_count'].astype(int)

In [45]:
df_poke['egg'] = df_poke['egg'].str.replace(' km', '').astype(float)

In [46]:
df_poke.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              151 non-null    int64
 1   num             151 non-null    int32
 2   name            151 non-null    object
 3   img             151 non-null    object
 4   type            151 non-null    object
 5   height          151 non-null    float64
 6   weight          151 non-null    float64
 7   candy           151 non-null    object
 8   candy_count     151 non-null    int32
 9   egg             73 non-null     float64
 10  spawn_chance    151 non-null    float64
 11  avg_spawns      151 non-null    float64
 12  spawn_time      151 non-null    object
 13  multipliers     70 non-null     object
 14  weaknesses      151 non-null    object
 15  next_evolution  70 non-null     object
 16  prev_evolution  72 non-null     object
dtypes: float64(5), int32(2), int64(1), object(9)
memory usage: 19.0+ KB

In [65]:
filename = "pokemon_pokedex.xlsx"
save_2_excel(df_poke, filename)

The Dataframe saved successfully as pokemon_pokedex.xlsx

In [51]:
filename2 = "pokemon_pokedex.csv"
df_poke.to_csv(filename2, index=False)